# Site settings
author: Diego Vallejos
title: A little bug
header-img: img/home-bg.png
email: xdiegovallejosx@gmail.com
copyright_name: Diego Vallejos
description: > # this means to ignore newlines until "baseurl:"
  The path of someone who used to hate math
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  diegovallejossalas

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
